CREATE DATABASE pizzas_db;
USE pizzas_db;

CREATE TABLE pizzas_db(
    id int NOT NULL AUTO_INCREMENT,
    pizza_type VARCHAR(200) NOT NULL,
    devoured BOOLEAN DEFAULT false,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    dt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);